export  const pivotArray = [
    {
        caption: "اجرت ساخت",
        filterTextForPivot: [
            "اجرت ساخت استیل حروف عادی",
            "اجرت ساخت استیل حروف های سخت",
            "اجرت ساخت چلنیوم حروف عادی",
            "اجرت ساخت حروف سوئدی  آسان",
            "اجرت ساخت نئون پلاستیک ( حروف استاندارد ) لبه 3 تا 8 سانت",
            "اجرت ساخت نئون فلکس ( حروف آسان )",
            "اجرت ساخت نئون فلکس ( حروف سخت )",
            "اجرت ساخت نئون فلکس ( لوگو و طرح آسان )",
        ] ,
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
    },
    {
        caption: "ترانس",
        filterTextForPivot:[
            "ترانس 200وات",
            "ترانس 300وات",
            "ترانس 400وات",

        ],
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
        showSubitems:true,
        subRowKey : "myContactTitle",
        subRowValue : "myQuantity"
    },
    {
        caption:"SMD",
        filterTextForPivot:[
            "SMD آفتابی با سیم کشی و منگنه",
            "SMD انبه ای با سیم کشی و منگنه",
            "SMD سفید با سیم کشی و منگنه",
            "اینجکشن آفتابی با سیم کشی و منگنه",
            "اینجکشن سفید با سیم کشی و منگنه",
        ],
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
    },
    {
        caption:"پلکسی",
        filterTextForPivot:[
            "پلکسی آبی آسمانی 2.8 میل کد 835",
            "پلکسی آبی کاربنی 2.8 میل کد 327",
            "پلکسی پیلاری 2.8 میل کد 238",
            "پلکسی پیلاری 2.8 میل کد245",
            "پلکسی دوغی 5میل",
            "پلکسی زیمنسی 2.8 میل کد 844",
            "پلکسی سبز 2.8 میل کد 348",
            "پلکسی سبز 2.8 میل کد 617",
            "پلکسی سفید 2.8 میل کد 433",
            "پلکسی شیشه ای شفاف 2.8 میل کد 0",
            "پلکسی صورتی 2.8 میل کد 100",
            "پلکسی طلایی آینه ای",
            "پلکسی قرمز  2.8 میل کد 136",
            "پلکسی مشکی 2.8 میل کد 502",
            "پلکسی نارنجی 2.8 میل کد 266",
            "پی وی سی ده میل",

        ],
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
    },
    {
        filterTextForPivot:[
            "چلنیوم  مشکی 9 سانت ساده",
            "چلنیوم  مشکی سوپر ساید",
            "چلنیوم سفید 9 سانت ساده",
            "چلنیوم طلایی 7 سانت پانچ",
            "چلنیوم طلایی 9 سانت پانچ",
            "چلنیوم طلایی 9سانت ساده",
            "چلنیوم طلایی سوپر ساید",
            "چلنیوم مشکی 9 سانت پانچ",
            "چلنیوم نقره ای  7 سانت ساده",
            "چلنیوم نقره ای 9 سانت پانچ",
            "چلنیوم نقره ای 9سانت ساده",
            "چلنیوم نقره ای سوپر ساید",
            "لبه سوئدی طلایی خشدار  7 سانت",
            "لبه سوئدی مشکی 7 سانت",
        ],
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
        caption:"چلنیوم",
    },
    {
        filterTextForPivot:["ورق استیل",],
        myKey:"myItemName",
        sumKey:"myTotalAmount",
        countKey:"myQuantity",
        caption:"ورق",
    },
]